import { GoogleGenAI } from "@google/genai";
import { StoryCategory, type Source, type Story } from "@prisma/client";
import { Prisma } from "@prisma/client";
import type { StoryScoreBreakdown } from "@bangladesh24/shared";
import { prisma } from "../db/client.js";
import { scoreStory } from "./scoringService.js";
import { mapStory } from "./storyMapper.js";

type StoryWithSource = Story & {
  source: Source;
};

interface GeneratedStoryScript {
  scriptBangla: string;
  captionBangla: string;
  hashtags: string;
  generationProvider: "gemini" | "fallback";
  notes: string;
}

interface GeminiScriptPayload {
  scriptBangla?: unknown;
  captionBangla?: unknown;
  hashtags?: unknown;
  category?: unknown;
  notes?: unknown;
}

const DEFAULT_MODEL = "gemini-2.5-flash";

function getApiKey() {
  return process.env.GEMINI_API_KEY?.trim() || null;
}

function getModel() {
  return process.env.GEMINI_MODEL?.trim() || DEFAULT_MODEL;
}

function normalizeHashtags(value: unknown) {
  if (Array.isArray(value)) {
    return value
      .map((item) => String(item).trim())
      .filter(Boolean)
      .map((item) => (item.startsWith("#") ? item : `#${item}`))
      .join(" ");
  }

  if (typeof value === "string") {
    return value
      .split(/\s+/)
      .map((item) => item.trim())
      .filter(Boolean)
      .map((item) => (item.startsWith("#") ? item : `#${item}`))
      .join(" ");
  }

  return "#Bangladesh24 #BangladeshNews #BDNews #NewsUpdate";
}

function stripMarkdownFence(value: string) {
  const trimmed = value.trim();
  const fencedMatch = trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);
  return fencedMatch ? fencedMatch[1].trim() : trimmed;
}

function parseGeminiJson(value: string): GeminiScriptPayload {
  const cleanValue = stripMarkdownFence(value);

  try {
    return JSON.parse(cleanValue) as GeminiScriptPayload;
  } catch {
    const firstBrace = cleanValue.indexOf("{");
    const lastBrace = cleanValue.lastIndexOf("}");

    if (firstBrace >= 0 && lastBrace > firstBrace) {
      return JSON.parse(cleanValue.slice(firstBrace, lastBrace + 1)) as GeminiScriptPayload;
    }

    throw new Error("Gemini response did not include valid JSON");
  }
}

function buildPrompt(story: StoryWithSource, extraInstruction?: string) {
  const location = story.district ?? story.division ?? "Bangladesh";

  return `
You are Bangladesh24's factual Bangla short-news script editor.

Create a reel-ready script from only the source facts below.
Do not add unverified facts, casualty counts, dates, allegations, causes, or locations.
Use simple modern Bangla, calm news tone, and short sentences.
Target 35-50 seconds for vertical Reels.
Mention the source by name in the script or caption.

Return only valid minified JSON with this shape:
{"scriptBangla":"...","captionBangla":"...","hashtags":["#Bangladesh24"],"category":"WEATHER","notes":"..."}

Allowed category values:
${Object.values(StoryCategory).join(", ")}

Story:
Title: ${story.title}
Summary: ${story.summary ?? "No summary provided"}
Content excerpt: ${story.content ?? story.summary ?? "No content provided"}
Source: ${story.source.name}
Link: ${story.link}
Published: ${story.publishedAt?.toISOString() ?? "Unknown"}
Location: ${location}
Current category: ${story.category}

Editorial instruction:
${extraInstruction?.trim() || "No extra instruction."}
`.trim();
}

function createFallbackScript(story: StoryWithSource): GeneratedStoryScript {
  const scoredStory = scoreStory(story);

  return {
    scriptBangla: scoredStory.scriptBangla,
    captionBangla: scoredStory.captionBangla,
    hashtags: scoredStory.hashtags,
    generationProvider: "fallback",
    notes: "Generated by deterministic fallback because Gemini was unavailable."
  };
}

async function generateWithGemini(story: StoryWithSource, extraInstruction?: string): Promise<GeneratedStoryScript> {
  const apiKey = getApiKey();

  if (!apiKey) {
    return createFallbackScript(story);
  }

  const ai = new GoogleGenAI({ apiKey });
  const response = await ai.models.generateContent({
    model: getModel(),
    contents: buildPrompt(story, extraInstruction),
    config: {
      temperature: 0.35,
      responseMimeType: "application/json"
    }
  });
  const payload = parseGeminiJson(response.text ?? "");

  if (typeof payload.scriptBangla !== "string" || typeof payload.captionBangla !== "string") {
    throw new Error("Gemini response is missing scriptBangla or captionBangla");
  }

  return {
    scriptBangla: payload.scriptBangla.trim(),
    captionBangla: payload.captionBangla.trim(),
    hashtags: normalizeHashtags(payload.hashtags),
    generationProvider: "gemini",
    notes: typeof payload.notes === "string" ? payload.notes : "Generated with Gemini."
  };
}

export async function generateStoryScript(storyId: string, extraInstruction?: string) {
  const story = await prisma.story.findUnique({
    where: { id: storyId },
    include: { source: true }
  });

  if (!story) {
    throw new Error("Story not found");
  }

  let generatedScript: GeneratedStoryScript;

  try {
    generatedScript = await generateWithGemini(story, extraInstruction);
  } catch (error) {
    generatedScript = createFallbackScript(story);
    generatedScript.notes =
      error instanceof Error
        ? `Gemini failed, fallback used: ${error.message}`
        : "Gemini failed, fallback used.";
  }

  const scoreBreakdown = story.scoreBreakdown as StoryScoreBreakdown | null;
  const updatedStory = await prisma.story.update({
    where: { id: story.id },
    data: {
      scriptBangla: generatedScript.scriptBangla,
      captionBangla: generatedScript.captionBangla,
      hashtags: generatedScript.hashtags,
      status: story.status === "NEW" ? "SCORED" : story.status,
      scoreBreakdown: scoreBreakdown
        ? ({
            ...scoreBreakdown,
            reason: `${scoreBreakdown.reason} Script: ${generatedScript.generationProvider}.`
          } as unknown as Prisma.InputJsonObject)
        : undefined
    },
    include: { source: true }
  });

  return {
    story: mapStory(updatedStory),
    generation: generatedScript
  };
}
