export interface DistrictInfo {
  name: string;
  division: string;
  aliases: string[];
}

export const DISTRICTS: DistrictInfo[] = [
  { name: "Bagerhat", division: "Khulna", aliases: ["bagerhat"] },
  { name: "Bandarban", division: "Chattogram", aliases: ["bandarban"] },
  { name: "Barguna", division: "Barishal", aliases: ["barguna"] },
  { name: "Barishal", division: "Barishal", aliases: ["barishal", "barisal"] },
  { name: "Bhola", division: "Barishal", aliases: ["bhola"] },
  { name: "Bogura", division: "Rajshahi", aliases: ["bogura", "bogra"] },
  { name: "Brahmanbaria", division: "Chattogram", aliases: ["brahmanbaria", "brahmanbaria"] },
  { name: "Chandpur", division: "Chattogram", aliases: ["chandpur"] },
  { name: "Chapai Nawabganj", division: "Rajshahi", aliases: ["chapai nawabganj", "nawabganj"] },
  { name: "Chattogram", division: "Chattogram", aliases: ["chattogram", "chittagong"] },
  { name: "Chuadanga", division: "Khulna", aliases: ["chuadanga"] },
  { name: "Cox's Bazar", division: "Chattogram", aliases: ["cox's bazar", "cox bazar", "coxsbazar"] },
  { name: "Cumilla", division: "Chattogram", aliases: ["cumilla", "comilla"] },
  { name: "Dhaka", division: "Dhaka", aliases: ["dhaka"] },
  { name: "Dinajpur", division: "Rangpur", aliases: ["dinajpur"] },
  { name: "Faridpur", division: "Dhaka", aliases: ["faridpur"] },
  { name: "Feni", division: "Chattogram", aliases: ["feni"] },
  { name: "Gaibandha", division: "Rangpur", aliases: ["gaibandha"] },
  { name: "Gazipur", division: "Dhaka", aliases: ["gazipur"] },
  { name: "Gopalganj", division: "Dhaka", aliases: ["gopalganj"] },
  { name: "Habiganj", division: "Sylhet", aliases: ["habiganj"] },
  { name: "Jamalpur", division: "Mymensingh", aliases: ["jamalpur"] },
  { name: "Jashore", division: "Khulna", aliases: ["jashore", "jessore"] },
  { name: "Jhalokathi", division: "Barishal", aliases: ["jhalokathi"] },
  { name: "Jhenaidah", division: "Khulna", aliases: ["jhenaidah"] },
  { name: "Joypurhat", division: "Rajshahi", aliases: ["joypurhat"] },
  { name: "Khagrachhari", division: "Chattogram", aliases: ["khagrachhari", "khagrachari"] },
  { name: "Khulna", division: "Khulna", aliases: ["khulna"] },
  { name: "Kishoreganj", division: "Dhaka", aliases: ["kishoreganj"] },
  { name: "Kurigram", division: "Rangpur", aliases: ["kurigram"] },
  { name: "Kushtia", division: "Khulna", aliases: ["kushtia"] },
  { name: "Lakshmipur", division: "Chattogram", aliases: ["lakshmipur", "laxmipur"] },
  { name: "Lalmonirhat", division: "Rangpur", aliases: ["lalmonirhat"] },
  { name: "Madaripur", division: "Dhaka", aliases: ["madaripur"] },
  { name: "Magura", division: "Khulna", aliases: ["magura"] },
  { name: "Manikganj", division: "Dhaka", aliases: ["manikganj"] },
  { name: "Meherpur", division: "Khulna", aliases: ["meherpur"] },
  { name: "Moulvibazar", division: "Sylhet", aliases: ["moulvibazar", "moulvi bazar"] },
  { name: "Munshiganj", division: "Dhaka", aliases: ["munshiganj"] },
  { name: "Mymensingh", division: "Mymensingh", aliases: ["mymensingh"] },
  { name: "Naogaon", division: "Rajshahi", aliases: ["naogaon"] },
  { name: "Narail", division: "Khulna", aliases: ["narail"] },
  { name: "Narayanganj", division: "Dhaka", aliases: ["narayanganj"] },
  { name: "Narsingdi", division: "Dhaka", aliases: ["narsingdi"] },
  { name: "Natore", division: "Rajshahi", aliases: ["natore"] },
  { name: "Netrokona", division: "Mymensingh", aliases: ["netrokona", "netrakona"] },
  { name: "Nilphamari", division: "Rangpur", aliases: ["nilphamari"] },
  { name: "Noakhali", division: "Chattogram", aliases: ["noakhali"] },
  { name: "Pabna", division: "Rajshahi", aliases: ["pabna"] },
  { name: "Panchagarh", division: "Rangpur", aliases: ["panchagarh"] },
  { name: "Patuakhali", division: "Barishal", aliases: ["patuakhali"] },
  { name: "Pirojpur", division: "Barishal", aliases: ["pirojpur"] },
  { name: "Rajbari", division: "Dhaka", aliases: ["rajbari"] },
  { name: "Rajshahi", division: "Rajshahi", aliases: ["rajshahi"] },
  { name: "Rangamati", division: "Chattogram", aliases: ["rangamati"] },
  { name: "Rangpur", division: "Rangpur", aliases: ["rangpur"] },
  { name: "Satkhira", division: "Khulna", aliases: ["satkhira"] },
  { name: "Shariatpur", division: "Dhaka", aliases: ["shariatpur"] },
  { name: "Sherpur", division: "Mymensingh", aliases: ["sherpur"] },
  { name: "Sirajganj", division: "Rajshahi", aliases: ["sirajganj"] },
  { name: "Sunamganj", division: "Sylhet", aliases: ["sunamganj"] },
  { name: "Sylhet", division: "Sylhet", aliases: ["sylhet"] },
  { name: "Tangail", division: "Dhaka", aliases: ["tangail"] },
  { name: "Thakurgaon", division: "Rangpur", aliases: ["thakurgaon"] }
];
